config/routes.rb
Rails.application.routes.draw do

  root "homes#top"

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }

  devise_for :admins, skip: [:registrations,:passwords] ,controllers: {
    sessions: "admins/sessions"
  }

  scope module: :user do
    resources :ramen_shops, only:[:create, :index, :edit, :update]
    get 'records/search'
    resources :records, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :likes, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy, :index]
    end
    resources :user, only:[:show, :edit, :update, :index] do
     resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  namespace :admin do
    resources :records, only:[:index, :show, :destroy]
    resources :comments, only:[:index, :show, :destroy]
    resources :user, only:[:index, :destroy]
    resources :genres,only:[:create, :index, :edit, :update, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :records, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  validates :name, presence: true
end

app/controllers/admin/user_controller.rb
class Admin::UserController < ApplicationController
  def index
    @users = User.all
  end

  def destroy
   @user = User.find(params[:id])
   @user.destroy
   redirect_to admin_user_index_path
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController

 def index
  @record = Record.find(params[:record_id])
  @comments =@record.comments
 end

 def create
  @record = Record.find(params[:record_id])
  @comment = current_user.comments.new(comment_params)
  @comment.record_id =@record.id
  @comment.save
  redirect_to request.referer
 end

  def destroy
   @record = Record.find(params[:record_id])
   @comment = @record.comments.find(params[:id])
   @comment.destroy
   redirect_to request.referer
  end

  private
  def comment_params
   params.require(:comment).permit(:comment)
  end

end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController

  def create
    @record =Record.find(params[:record_id])
    like =current_user.likes.new(record_id: @record.id)
    like.save
  end


  def destroy
    @record =Record.find(params[:record_id])
    like = current_user.likes.find_by(record_id: @record.id)
    like.destroy
  end

end

app/controllers/user/ramen_shops_controller.rb
class User::RamenShopsController < ApplicationController

  def index

  end

  def create
   @ramen_shop = Ramen_Shop.new(ramen_shop_params)
   if @ramen_shop.save
     redirect_to ramen_shops_path
   else
     render :index
   end
  end

  def show
   @ramen_shop = Ramen_Shop.find(params[:id])
  end

  def edit
    @ramen_shop = Ramen_Shop.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    ramen_shop_list = params[:record][:ramen_shop].split(',')
    if @record.update(record_paramas)
       @record.save_ramen_shops(ramen_shop_list)
       redirect_to record_path(@record.id)
    else
      render index
    end
  end

  private

  def ramen_shop_params
    params.require(:ramen_shop).permit(:name)
  end

end

app/controllers/user/records_controller.rb
class User::RecordsController < ApplicationController

  def new
   @record = Record.new
  end

  def index
   @total_records =Record.all
   @records =Record.page(params[:page])
  end

  def create
   @record = Record.new(record_params)
   @record.user_id = current_user.id
   if @record.save
    redirect_to record_path(@record.id)
   else
    render "new"
   end
  end

  def show
   @record = Record.find(params[:id])
   @genre = Genre.find(@record.genre_id)
   gon.record = @record
   @user = @record.user
   @comment = Comment.new
   @comments = @record.comments
  end

  def edit
   @record = Record.find(params[:id])
   if @record.user == current_user
    render "edit"
   else
    render "index"
   end
  end

  def update
   @record = Record.find(params[:id])
   if @record.update(record_params)
    redirect_to record_path(@record.id)
   else
    render "edit"
   end
  end

  def destroy
    @record = Record.find(params[:id])
    @user = @record.user
    @record.destroy
    redirect_to user_path(@user.id)
  end

  private

  def record_params
   params.require(:record).permit(:user_id, :name, :shop_name, :caption, :rate, :address, :image, :date, :genre_id)
  end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
 before_action :authenticate_user!

 def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
 end

 def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
 end

 def followings
    user = User.find(params[:user_id])
    @users = user.followings
 end

 def followers
    user = User.find(params[:user_id])
    @users = user.followers
 end

end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
end

app/controllers/user/user_controller.rb
class User::UserController < ApplicationController
  def show
   @user = User.find(params[:id])
   @records = @user.records
  end

 def index
   @total_users = User.all
   @users = Kaminari.paginate_array(@total_users).page(params[:page]).per(7)
 end

 def edit
   @user = User.find(params[:id])
   if @user == current_user
    render "edit"
   else
    redirect_to user_path(current_user)
   end
 end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
    flash[:notice] = "successfully"
    redirect_to user_path(current_user)
   else
    render :edit
   end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction,:profile_image)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit


  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

   def after_update_path_for(resource)
     user_path(@user)
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/likes_helper.rb
module User::LikesHelper
end

app/helpers/user/ramen_shops_helper.rb
module User::RamenShopsHelper
end

app/helpers/user/records_helper.rb
module User::RecordsHelper
end

app/views/user/user/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h2>メンバー情報変更</h2>
      <% if @user.errors.any? %>
      <%= @user.errors.count %>error prohibited this obj from being saved
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
         <%= form_with model: @user do |f| %>
          <div class="form-group">
            <label for="user _name">ユーザー名</label>
            <%= f.text_field :name,class:"form-control" %>
          </div>
          <div class="form-group">
            <label for="user_image">ユーザー画像</label><br>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">自己紹介</label>
            <%= f.text_field :introduction,class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit :"更新",class:"btn btn-lg btn-block btn-secondary mt-4" %>
          </div>
          <% end %>
      </div>
     </div>
  </div>
</main>

app/views/user/user/index.html.erb
<div class="contair">
<h2 class="text-center">
 TOTAL</br>(<%= @total_users.count %>ユーザー)
</h2>
<div class="scroll-list jscroll">
<% @users.each do |user| %>
<div class="card w-50 mx-auto mt-4">
 <div class="row no-gutters">
  <div class="col-lg-6">
   <%= link_to user_path(user) do %>
    <%= image_tag user.get_profile_image(200,200) %>
   <% end %>
  </div>
  <div class="col-lg-6">
  　<div class="card-body">
     <h4 class="card-title"><%= user.name %></h4>
     <p class="card-text">投稿数<%= user.records.count %></p>
     <small class="text-muted">フォロー数：<%= user.followings.count %></small>
     <small class="text-muted">フォロワー数：<%= user.followers.count %></small>
    </div>
  </div>
 </div>
</div>
<% end %>

   <%= paginate @users %>
　</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
<script>
$(window).on('scroll', function() {
    scrollHeight = $(document).height();
    scrollPosition = $(window).height() + $(window).scrollTop();
    if ( (scrollHeight - scrollPosition) / scrollHeight <= 0.05) {
          $('.jscroll').jscroll({
            contentSelector: '.scroll-list',
            nextSelector: 'span.next:last a'
          });
    }
});
</script>

app/views/user/user/show.html.erb
<div class="container">
<table class="table table-borderless">
<tr>
 <td><%= image_tag @user.get_profile_image(200,200) %></td>
 <td class="records">投稿</br><%= @user.records.count %></td>
 <td class="followings">フォロー数</br><%=link_to @user.followings.count ,user_followings_path(@user.id),class:"text-dark" %></td>
 <td class="followers">フォロワー数</br><%=link_to @user.followers.count ,user_followers_path(@user.id),class:"text-dark"  %></td>
 <td>
 	<% unless current_user == @user %>
 	<% if current_user.following?(@user) %>
   <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete,class:"btn btn-secondary" %>
  <% else %>
   <%= link_to "フォローする", user_relationships_path(@user.id), method: :post,class:"btn btn-primary" %>
  <% end %>
  <% end %>
 </td>
</tr>
</table>
<table>
<tr>
 <th><%= @user.name %></th>
<tr>
<td>
<tr>
	<td><%= @user.introduction %></td>
</tr>
</table>
  <% if @user == current_user %>
   <%= link_to "プロフィール編集", edit_user_path(@user),class:"btn btn-secondary" %>
  <% end %>
 <hr class="featurette-divider">
<div class="row">
<% @records.each do |record| %>
<div class="col-lg-4 col-md-6 mb-4">
 	<%= link_to record_path(record) do %>
    <%= image_tag record.get_image,size: '200x200' %>
  <% end %>
 </div>
<% end %>
</div>
</div>